name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: download avcodec
      run: |
        sudo apt-get update
        sudo apt-get install build-essential clang libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev libswscale-dev
    - name: download optional dependencies
      run: sudo apt-get install libglfw3-dev
    - name: make
      run: make
    - name: run tests
      run: bash ./run_tests.sh
